### ISSUE TITLE
Parallel chain error

### ISSUE THREAD

**Issue by ericward-noaa** [fate-ewi/bayesdfa#1]
When running these models in a loop, there is sometimes an issue related to parallel chains in Stan, and the following error gets thrown:

Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Calls: <Anonymous> ... doTryCatch -> sendData -> sendData.SOCK0node -> serialize
Execution halted

**Comment by ericward-noaa** [comment]
The solution here is to run a single chain, or run everything on 1 core (not parallel). This seems like a minor bug in Stan or the parallel implementation, 
https://github.com/stan-dev/rstanarm/issues/28

**Comment by seananderson** [comment]
Possibly memory related. Or an issue with 4 virtual cores on a true 2 core machine. Ideally n - 1 cores used:
https://stackoverflow.com/a/31789312
http://gforge.se/2015/02/how-to-go-parallel-in-r-basics-tips/#Memory_load
