### ISSUE TITLE
Functions to return fitted values, trends, and loadings as data frames

### ISSUE THREAD

**Issue by michaelmalick** [fate-ewi/bayesdfa#14]
It would be useful to have a set of functions (or a single function) to extract and return the fitted values, trends, and loadings as 'tidy' data frames. From what I can tell, the functions `plot_fitted`, `plot_trends` and `plot_loadings` contain the code to produce these data frames, but there isn't a way to return the data frames that are used to create the plots (please correct me if I missed something). My main use case here is to use the data frames to produce alternative graphics of these outputs.

I am happy to code these up if it would be useful. I was thinking of having separate functions for each of the fitted values, trends, and loadings, which would mirror the plot function structure. These functions could then be used in the corresponding plot functions to get the data frames necessary to generate the plots.

**Comment by michaelmalick** [comment]
@ericward-noaa  I pushed the branch `dataframes`, which includes three commits that allow getting the fitted values, trends, and loading as data frames. In short, I extracted the code from the corresponding plot functions to create the three new functions (`dfa_fitted`, `dfa_trends`, `dfa_loadings`) that return the outputs as a data frame and then call these new functions in the plot functions to generate the data frames for the `ggplot` calls.

**Comment by seananderson** [comment]
That's awesome, thanks @michaelmalick

**Comment by ericward-noaa** [comment]
Thanks @michaelmalick ! just merged in these changes, and added you as an author. 

I've been meaning to fire off a new version to CRAN, and will do that next week. Also working with the NOAA Fisheries Toolbox to have the new version featured on their site
