### ISSUE TITLE
dfa_cv cannot running

### ISSUE THREAD

**Issue by 123gaozihui** [fate-ewi/bayesdfa#18]
Expecting you will see this and answer my question.
I'm studying the bayesdfa package. But when I running the "dfa_cv", it has an Error. 
          >set.seed(42)
          > s <- sim_dfa(num_trends = 1, num_years = 20, num_ts = 3)
          > obs <- c(s$y_sim[1, ], s$y_sim[2, ], s$y_sim[3, ])
          > long <- data.frame("obs" = obs, "ts" = sort(rep(1:3, 20)),
          +                    "time" = rep(1:20, 3))
          > obs_covar <- expand.grid("time" = 1:20, "timeseries" = 1:3,
          +                          "covariate" = 1:2)
          > obs_covar$value <- rnorm(nrow(obs_covar), 0, 0.1)
          > obs <- c(s$y_sim[1, ], s$y_sim[2, ], s$y_sim[3, ])
          > m <- fit_dfa(y = long, iter = 50, chains = 1, obs_covar = obs_covar,
          +              data_shape = "long")
          > fit_cv <- dfa_cv(m, cv_method = "loocv", n_folds = 5, iter = 50, chains = 1)
          错误: passing unknown arguments: zscore.
          此外: Warning message:
          In dfa_cv(m, cv_method = "loocv", n_folds = 5, iter = 50, chains = 1) :
          the vector fold_ids containing fold ids is null, so random folds are being used

When I set "scale=zscore" in the "fit_dfa", it still has the same wrong.

          > m <- fit_dfa(y = long, iter = 50, chains = 1, obs_covar = obs_covar,scale="zscore",
          +              data_shape = "long")
          > fit_cv <- dfa_cv(m, cv_method = "loocv", n_folds = 5, iter = 50, chains = 1)
          错误: passing unknown arguments: zscore.
          此外: Warning message:
          In dfa_cv(m, cv_method = "loocv", n_folds = 5, iter = 50, chains = 1) :
          the vector fold_ids containing fold ids is null, so random folds are being used

**Comment by ericward-noaa** [comment]
Sorry that you had issues with this. I found a bug in the code that was causing problems, and have fixed it with this commit:
https://github.com/fate-ewi/bayesdfa/commit/f8f6583f9e8f9613145ea910909fd16eacdba2dd

Let me know if you're having problems still. Thanks!

**Comment by 123gaozihui** [comment]
Dear professor Ward:
  Thank you very much for your reply. Your assistance has been invaluable to me. Thank you so much again.
  Best wishes!
  Gao Zihui


| |
高子惠
|
|
***@***.***
|
签名由网易邮箱大师定制
On 11/30/2021 22:15，Eric ***@***.***> wrote：

Closed #18.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
