### ISSUE TITLE
Long-format data "time" needs rescaling to start at "1"

### ISSUE THREAD

**Issue by larogers123** [fate-ewi/bayesdfa#31]
When running fit_dfa() with long-format data, if the "time" column does not start at 1, the model still attempts to estimate starting at time-step 1. This becomes an issue when using data with "time" as years, e.g. 1980-2020, as the model appears to estimate trends for years 1:2020, with no data for the first 1,979 time steps, and becomes very slow. I see a commented line of code at line 241:

    # y$time <- y$time - min(y[["time"]]) + 1 # min time now = 1

This would appear to address the issue, although lose the numeric year information without warning.

**Comment by ericward-noaa** [comment]
Thanks for flagging this Lauren -- I just made the change, and uncommented this line (and included a warning message). Closing this issue for now, but report back if you run into any other problems
